find_path(LIBPROTOBUF_INCLUDE_DIR 
		NAMES arena.h
		HINTS ${PROTOBUF_PATH_ROOT}
		PATH_SUFFIXES include/google/protobuf)

if(WIN32)
	find_library(LIBPROTOBUF_LIBRARY_DEBUG
		NAMES libprotobufd
		HINTS ${PROTOBUF_PATH_ROOT}
		PATH_SUFFIXES x64/lib)
	find_library(LIBPROTOBUF_LIBRARY_RELEASE
        NAMES libprotobuf
        HINTS ${PROTOBUF_PATH_ROOT}
        PATH_SUFFIXES x64/lib)		
	set(LIBPROTOBUF_LIBRARIES_DEBUG ${LIBPROTOBUF_LIBRARY_DEBUG})
	set(LIBPROTOBUF_LIBRARIES_RELEASE ${LIBPROTOBUF_LIBRARY_RELEASE})
else(WIN32)
	find_library(LIBPROTOBUF_LIBRARY
			NAMES protobuf
			HINTS ${PROTOBUF_PATH_ROOT}
			PATH_SUFFIXES bin lib)			
	set(LIBPROTOBUF_LIBRARIES ${LIBPROTOBUF_LIBRARY})	
endif(WIN32)

set(LIBPROTOBUF_INCLUDE_DIRS ${LIBPROTOBUF_INCLUDE_DIR}/../../)

include(FindPackageHandleStandardArgs)

if(WIN32)
	find_package_handle_standard_args(LIBPROTOBUF DEFAULT_MSG LIBPROTOBUF_LIBRARY_DEBUG LIBPROTOBUF_LIBRARY_RELEASE LIBPROTOBUF_INCLUDE_DIRS)
else()
	find_package_handle_standard_args(LIBPROTOBUF DEFAULT_MSG LIBPROTOBUF_LIBRARY LIBPROTOBUF_INCLUDE_DIRS)
endif(WIN32)