find_path(POCO_CRYPTO_INCLUDE_DIR 
		NAMES Poco/Crypto/Crypto.h
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES include)

find_library(POCO_CRYPTO_LIBRARY
		NAMES PocoCrypto
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES bin lib)
		
set(POCO_CRYPTO_LIBRARIES ${POCO_CRYPTO_LIBRARY})
set(POCO_CRYPTO_INCLUDE_DIRS ${POCO_CRYPTO_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)	

find_package_handle_standard_args(POCO_CRYPTO DEFAULT_MSG POCO_CRYPTO_LIBRARY POCO_CRYPTO_INCLUDE_DIR)
