
if(WIN32)
	FIND_PATH(GDAL_INCLUDE_DIR 
		NAMES ogr_srs_api.h
		HINTS ${GDAL_PATH_ROOT}
		PATH_SUFFIXES include)
	FIND_LIBRARY(GDAL_LIBRARY
		NAMES gdal_i 
		HINTS ${GDAL_PATH_ROOT}
		PATH_SUFFIXES lib)
else()	
	FIND_PATH(GDAL_INCLUDE_DIR 
		NAMES ogr_srs_api.h
		HINTS ${GDAL_PATH_ROOT}
		PATH_SUFFIXES include/gdal)
	FIND_LIBRARY(GDAL_LIBRARY
		NAMES gdal 
		HINTS ${GDAL_PATH_ROOT}
		PATH_SUFFIXES bin lib)
endif(WIN32)

set(GDAL_LIBRARIES ${GDAL_LIBRARY})
set(GDAL_INCLUDE_DIRS ${GDAL_INCLUDE_DIR})
message(STATUS "GDAL_PATH_ROOT：${GDAL_PATH_ROOT}")
message(STATUS "GDAL_INCLUDE_DIR：${GDAL_INCLUDE_DIR}")
message(STATUS "GDAL_LIBRARY：${GDAL_LIBRARY}")

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(Gdal DEFAULT_MSG GDAL_LIBRARY GDAL_INCLUDE_DIR)