find_path(POCO_NETSSL_INCLUDE_DIR 
		NAMES Poco/Net/NetSSL.h
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES include)

find_library(POCO_NETSSL_LIBRARY
		NAMES PocoNetSSL
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES bin lib)
		
set(POCO_NETSSL_LIBRARIES ${POCO_NETSSL_LIBRARY})
set(POCO_NETSSL_INCLUDE_DIRS ${POCO_NETSSL_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)	

find_package_handle_standard_args(POCO_NETSSL DEFAULT_MSG POCO_NETSSL_LIBRARY POCO_NETSSL_INCLUDE_DIR)
