find_path(POCO_FOUNDATION_INCLUDE_DIR 
		NAMES Poco/Foundation.h
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES include)

find_library(POCO_FOUNDATION_LIBRARY
		NAMES PocoFoundation
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES bin lib)
		
set(POCO_FOUNDATION_LIBRARIES ${POCO_FOUNDATION_LIBRARY})
set(POCO_FOUNDATION_INCLUDE_DIRS ${POCO_FOUNDATION_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)	

find_package_handle_standard_args(POCO_FOUNDATION DEFAULT_MSG POCO_FOUNDATION_LIBRARY POCO_FOUNDATION_INCLUDE_DIR)
