find_path(METADATAPROCESSING_INCLUDE_DIR
        NAMES jo_meta_data_structure.h
        HINTS ${METADATAPROCESSING_PATH_ROOT}
        PATH_SUFFIXES include)

find_library(METADATAPROCESSING_LIBRARY
		NAMES jo_meta_data_processing
		HINTS ${METADATAPROCESSING_PATH_ROOT}
		PATH_SUFFIXES bin lib)

set(METADATAPROCESSING_LIBRARIES ${METADATAPROCESSING_LIBRARY})
set(METADATAPROCESSING_INCLUDE_DIRS ${METADATAPROCESSING_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(MetaDataProcessing DEFAULT_MSG METADATAPROCESSING_LIBRARY METADATAPROCESSING_INCLUDE_DIR)