find_path(OPENCV_CORE_INCLUDE_DIR 
		NAMES core.hpp
		HINTS ${OPENCV_PATH_ROOT}
		PATH_SUFFIXES include/opencv2)

if(WIN32)
	find_library(OPENCV_CORE_LIBRARY_DEBUG
		NAMES opencv_core420d
		HINTS ${OPENCV_PATH_ROOT}
		PATH_SUFFIXES x64/vc15/lib)
	find_library(OPENCV_CORE_LIBRARY_RELEASE
        NAMES opencv_core420
        HINTS ${OPENCV_PATH_ROOT}
        PATH_SUFFIXES x64/vc15/lib)
	set(OPENCV_CORE_LIBRARIES_DEBUG ${OPENCV_CORE_LIBRARY_DEBUG})
	set(OPENCV_CORE_LIBRARIES_RELEASE ${OPENCV_CORE_LIBRARY_RELEASE})
else(WIN32)
	find_library(OPENCV_CORE_LIBRARY
			NAMES opencv_core
			HINTS ${OPENCV_PATH_ROOT}
			PATH_SUFFIXES bin lib)			
	set(OPENCV_CORE_LIBRARIES ${OPENCV_CORE_LIBRARY})
endif(WIN32)

set(OPENCV_CORE_INCLUDE_DIRS ${OPENCV_CORE_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

if(WIN32)
	find_package_handle_standard_args(OPENCV_CORE DEFAULT_MSG OPENCV_CORE_LIBRARY_DEBUG OPENCV_CORE_LIBRARY_RELEASE OPENCV_CORE_INCLUDE_DIR)
else()
	find_package_handle_standard_args(OPENCV_CORE DEFAULT_MSG OPENCV_CORE_LIBRARY OPENCV_CORE_INCLUDE_DIR)
endif(WIN32)