find_path(BOOST_SYSTEM_INCLUDE_DIR 
		NAMES system.hpp asio.hpp
		HINTS ${BOOST_PATH_ROOT}
		PATH_SUFFIXES boost)

if(WIN32)
	find_library(BOOST_SYSTEM_LIBRARY_DEBUG
		NAMES libboost_system-vc141-mt-sgd-x64-1_78
		HINTS ${BOOST_PATH_ROOT}
		PATH_SUFFIXES lib64-msvc-14.1)
	find_library(BOOST_SYSTEM_LIBRARY_RELEASE
        NAMES libboost_system-vc141-mt-s-x64-1_78
        HINTS ${BOOST_PATH_ROOT}
        PATH_SUFFIXES lib64-msvc-14.1)		
	set(BOOST_SYSTEM_LIBRARIES_DEBUG ${BOOST_SYSTEM_LIBRARY_DEBUG})
	set(BOOST_SYSTEM_LIBRARIES_RELEASE ${BOOST_SYSTEM_LIBRARY_RELEASE})
else(WIN32)
	find_library(BOOST_SYSTEM_LIBRARY
			NAMES boost_system
			HINTS ${BOOST_PATH_ROOT}
			PATH_SUFFIXES bin lib)
	set(BOOST_SYSTEM_LIBRARIES ${BOOST_SYSTEM_LIBRARY})	
endif(WIN32)

set(BOOST_SYSTEM_INCLUDE_DIRS ${BOOST_SYSTEM_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

if(WIN32)
	find_package_handle_standard_args(BOOST_SYSTEM DEFAULT_MSG BOOST_SYSTEM_LIBRARY_DEBUG BOOST_SYSTEM_LIBRARY_RELEASE BOOST_SYSTEM_INCLUDE_DIR)
else()
	find_package_handle_standard_args(BOOST_SYSTEM DEFAULT_MSG BOOST_SYSTEM_LIBRARY BOOST_SYSTEM_INCLUDE_DIR)
endif(WIN32)