find_path(POCO_JSON_INCLUDE_DIR 
		NAMES Poco/JSON/JSON.h
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES include)

find_library(POCO_JSON_LIBRARY
		NAMES PocoJSON
		HINTS ${POCO_PATH_ROOT}
		PATH_SUFFIXES bin lib)
		
set(POCO_JSON_LIBRARIES ${POCO_JSON_LIBRARY})
set(POCO_JSON_INCLUDE_DIRS ${POCO_JSON_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)	

find_package_handle_standard_args(POCO_JSON DEFAULT_MSG POCO_JSON_LIBRARY POCO_JSON_INCLUDE_DIR)
