find_path(BOOST_THREAD_INCLUDE_DIR 
		NAMES thread.hpp
		HINTS ${BOOST_PATH_ROOT}
		PATH_SUFFIXES boost)

if(WIN32)
	find_library(BOOST_THREAD_LIBRARY_DEBUG
		NAMES libboost_thread-vc141-mt-sgd-x64-1_78
		HINTS ${BOOST_PATH_ROOT}
		PATH_SUFFIXES lib64-msvc-14.1)
	find_library(BOOST_THREAD_LIBRARY_RELEASE
        NAMES libboost_thread-vc141-mt-s-x64-1_78
        HINTS ${BOOST_PATH_ROOT}
        PATH_SUFFIXES lib64-msvc-14.1)		
	set(BOOST_THREAD_LIBRARIES_DEBUG ${BOOST_THREAD_LIBRARY_DEBUG})
	set(BOOST_THREAD_LIBRARIES_RELEASE ${BOOST_THREAD_LIBRARY_RELEASE})
else(WIN32)
	find_library(BOOST_THREAD_LIBRARY
			NAMES boost_thread
			HINTS ${BOOST_PATH_ROOT}
			PATH_SUFFIXES bin lib)			
	set(BOOST_THREAD_LIBRARIES ${BOOST_THREAD_LIBRARY})	
endif(WIN32)

set(BOOST_THREAD_INCLUDE_DIRS ${BOOST_THREAD_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

if(WIN32)
	find_package_handle_standard_args(BOOST_THREAD DEFAULT_MSG BOOST_THREAD_LIBRARY_DEBUG BOOST_THREAD_LIBRARY_RELEASE BOOST_THREAD_INCLUDE_DIR)
else()
	find_package_handle_standard_args(BOOST_THREAD DEFAULT_MSG BOOST_THREAD_LIBRARY BOOST_THREAD_INCLUDE_DIR)
endif(WIN32)