find_path(BOOST_FILESYSTEM_INCLUDE_DIR 
		NAMES filesystem.hpp
		HINTS ${BOOST_PATH_ROOT}
		PATH_SUFFIXES boost)

if(WIN32)
	find_library(BOOST_FILESYSTEM_LIBRARY_DEBUG
		NAMES libboost_filesystem-vc141-mt-sgd-x64-1_78
		HINTS ${BOOST_PATH_ROOT}
		PATH_SUFFIXES lib64-msvc-14.1)
	find_library(BOOST_FILESYSTEM_LIBRARY_RELEASE
        NAMES libboost_filesystem-vc141-mt-s-x64-1_78
        HINTS ${BOOST_PATH_ROOT}
        PATH_SUFFIXES lib64-msvc-14.1)		
	set(BOOST_FILESYSTEM_LIBRARIES_DEBUG ${BOOST_FILESYSTEM_LIBRARY_DEBUG})
	set(BOOST_FILESYSTEM_LIBRARIES_RELEASE ${BOOST_FILESYSTEM_LIBRARY_RELEASE})
else(WIN32)
	find_library(BOOST_FILESYSTEM_LIBRARY
			NAMES boost_filesystem
			HINTS ${BOOST_PATH_ROOT}
			PATH_SUFFIXES bin lib)
	set(BOOST_FILESYSTEM_LIBRARIES ${BOOST_FILESYSTEM_LIBRARY})	
endif(WIN32)

set(BOOST_FILESYSTEM_INCLUDE_DIRS ${BOOST_FILESYSTEM_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

if(WIN32)
	find_package_handle_standard_args(BOOST_FILESYSTEM DEFAULT_MSG BOOST_FILESYSTEM_LIBRARY_DEBUG BOOST_FILESYSTEM_LIBRARY_RELEASE BOOST_FILESYSTEM_INCLUDE_DIR)
else()
	find_package_handle_standard_args(BOOST_FILESYSTEM DEFAULT_MSG BOOST_FILESYSTEM_LIBRARY BOOST_FILESYSTEM_INCLUDE_DIR)
endif(WIN32)